# Generated by Django 4.2.17 on 2024-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Author')),
                ('cover_image', models.FileField(upload_to='books/', verbose_name='Cover Image')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
