# Generated by Django 4.2.17 on 2024-12-10 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: " + 999999999". Up to 10 digits allowed.', regex='^\\+?1?\\d{10}$')], verbose_name='Phone Number'),
        ),
    ]
